name: Deploy

on: [push]

jobs:
  build_site:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Install surfer
        run: npm -g install cloudron-surfer

      - name: Upload
        env:
          SURFER_TOKEN: ${{ secrets.SURFER_TOKEN }}
          SURFER_HOST: ${{ secrets.SURFER_HOST }}
          SURFER_FOLDER: ${{ secrets.SURFER_FOLDER }}
        run: surfer put --token "$SURFER_TOKEN" --server "$SURFER_HOST" build/* "$SURFER_FOLDER"
